// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjk9lbgBzK6rNPuLKs_w58bib3BquEK0U',
    appId: '1:351864218835:web:1597b3e891176d63442026',
    messagingSenderId: '351864218835',
    projectId: 'l-final-8f472',
    authDomain: 'l-final-8f472.firebaseapp.com',
    storageBucket: 'l-final-8f472.firebasestorage.app',
    measurementId: 'G-Z23TBLTKC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8vXwdDL-M2tFMHGFfnliBp-IyS0KOf-Y',
    appId: '1:351864218835:android:ad7715903fb13178442026',
    messagingSenderId: '351864218835',
    projectId: 'l-final-8f472',
    storageBucket: 'l-final-8f472.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu3Sl7LZotnnGn_QPzFXTEFq0Qv0QAZPo',
    appId: '1:351864218835:ios:daa48e72c46d0732442026',
    messagingSenderId: '351864218835',
    projectId: 'l-final-8f472',
    storageBucket: 'l-final-8f472.firebasestorage.app',
    androidClientId: '351864218835-0ralq5g4986h091m8afq9g53dh6vcd4p.apps.googleusercontent.com',
    iosClientId: '351864218835-kvvttsnqudg0iscmoqr40bom7hlg0ecm.apps.googleusercontent.com',
    iosBundleId: 'com.stylebox.dashboard',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu3Sl7LZotnnGn_QPzFXTEFq0Qv0QAZPo',
    appId: '1:351864218835:ios:daa48e72c46d0732442026',
    messagingSenderId: '351864218835',
    projectId: 'l-final-8f472',
    storageBucket: 'l-final-8f472.firebasestorage.app',
    androidClientId: '351864218835-0ralq5g4986h091m8afq9g53dh6vcd4p.apps.googleusercontent.com',
    iosClientId: '351864218835-kvvttsnqudg0iscmoqr40bom7hlg0ecm.apps.googleusercontent.com',
    iosBundleId: 'com.stylebox.dashboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjk9lbgBzK6rNPuLKs_w58bib3BquEK0U',
    appId: '1:351864218835:web:1597b3e891176d63442026',
    messagingSenderId: '351864218835',
    projectId: 'l-final-8f472',
    authDomain: 'l-final-8f472.firebaseapp.com',
    storageBucket: 'l-final-8f472.firebasestorage.app',
    measurementId: 'G-Z23TBLTKC5',
  );
}
