name: Flutter CI and Build APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # سحب الكود (تم التحديث لـ v4 لأفضل أداء)
    - name: Checkout code
      uses: actions/checkout@v4

    # تجهيز بيئة الجافا المطلوبة للأندرويد
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.x'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Analyze project source
      run: flutter analyze

    - name: Run tests
      run: flutter test

    # بناء ملف الـ APK
    - name: Build APK
      run: flutter build apk --release

    # رفع الـ APK عشان تقدر تحمله من صفحة GitHub
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
