// Generated by Flutter Assets

// ignore_for_file: unused_field, camel_case_types, non_constant_identifier_names, library_private_types_in_public_api

import 'package:flutter/widgets.dart';

class Assets extends StatelessWidget {
  final AssetsData assets;
  final Widget child;

  const Assets({super.key, required this.assets, required this.child});

  static AssetsData of(BuildContext context) {
    final widget = context
        .dependOnInheritedWidgetOfExactType<_InheritedAssets>();
    return widget?.assets ?? AssetsData.light();
  }

  @override
  Widget build(BuildContext context) {
    return _InheritedAssets(assets: assets, child: child);
  }
}

class _InheritedAssets extends InheritedWidget {
  final AssetsData assets;

  const _InheritedAssets({required this.assets, required super.child});

  @override
  bool updateShouldNotify(covariant _InheritedAssets oldWidget) =>
      assets != oldWidget.assets;
}

class AssetsData {
  static AssetsData? _light;
  static AssetsData? _dark;

  factory AssetsData.light() =>
      _light ??= AssetsData._(brightness: Brightness.light);
  factory AssetsData.dark() =>
      _dark ??= AssetsData._(brightness: Brightness.dark);
  factory AssetsData.brightness(Brightness brightness) =>
      brightness == Brightness.light ? AssetsData.light() : AssetsData.dark();

  final Brightness _brightness;

  AssetsData._({required Brightness brightness})
    : _brightness = brightness,
      fonts = _assets_fonts_dart._(brightness: brightness),
      images = _assets_images_dart._(brightness: brightness);

  final _assets_fonts_dart fonts;
  final _assets_images_dart images;
}

class _assets_fonts_dart {
  final Brightness _brightness;

  _assets_fonts_dart._({required Brightness brightness})
    : _brightness = brightness;

  final Cairo_Bold_ttf = 'assets/fonts/Cairo-Bold.ttf';
  final Cairo_Medium_ttf = 'assets/fonts/Cairo-Medium.ttf';
  final Cairo_Regular_ttf = 'assets/fonts/Cairo-Regular.ttf';
  final Cairo_SemiBold_ttf = 'assets/fonts/Cairo-SemiBold.ttf';
}

class _assets_images_dart {
  final Brightness _brightness;

  _assets_images_dart._({required Brightness brightness})
    : _brightness = brightness,
      bold = _assets_images_bold_dart._(brightness: brightness),
      outline = _assets_images_outline_dart._(brightness: brightness);

  final _assets_images_bold_dart bold;
  final _assets_images_outline_dart outline;

  final app_icon_jpg = 'assets/images/app_icon.jpg';
  final Avatar_1_png = 'assets/images/Avatar_1.png';
  final Avatar_2_png = 'assets/images/Avatar_2.png';
  final Avatar_3_png = 'assets/images/Avatar_3.png';
  final Check_svg = 'assets/images/Check.svg';
  final edit_svg = 'assets/images/edit.svg';
  final facebook_icon_svg = 'assets/images/facebook_icon.svg';
  final google_icon_svg = 'assets/images/google_icon.svg';
  final location_svg = 'assets/images/location.svg';
  final notification_svg = 'assets/images/notification.svg';
  final trash_svg = 'assets/images/trash.svg';
  final onboardingImage_png = 'assets/images/onboardingImage.png';
  final onboarding_image1_jpg = 'assets/images/onboarding_image1.jpg';
}

class _assets_images_bold_dart {
  final Brightness _brightness;

  _assets_images_bold_dart._({required Brightness brightness})
    : _brightness = brightness;

  final home_svg = 'assets/images/bold/home.svg';
  final products_svg = 'assets/images/bold/products.svg';
  final shopping_cart_svg = 'assets/images/bold/shopping-cart.svg';
  final user_svg = 'assets/images/bold/user.svg';
}

class _assets_images_outline_dart {
  final Brightness _brightness;

  _assets_images_outline_dart._({required Brightness brightness})
    : _brightness = brightness;

  final home_svg = 'assets/images/outline/home.svg';
  final products_svg = 'assets/images/outline/products.svg';
  final shopping_cart_svg = 'assets/images/outline/shopping-cart.svg';
  final user_svg = 'assets/images/outline/user.svg';
}
