import 'package:stylebox/core/entities/product_entity.dart';

/// Demo Style Boxes shown while Firestore has no real boxes yet.
/// They disappear automatically as soon as a store adds a box from the
/// dashboard. Ids start with `demo-` so they can't be reserved.
bool isDemoProduct(ProductEntity product) =>
    product.documentId.startsWith('demo-');

// Pins for the two demo stores on the map.
const _zayedAddress = 'Arkan Plaza, Sheikh Zayed, Giza';
const _zayedLat = 30.0214;
const _zayedLng = 30.9867;
const _zamalekAddress = '26th of July St, Zamalek, Cairo';
const _zamalekLat = 30.0617;
const _zamalekLng = 31.2194;

final List<ProductEntity> demoProducts = [
  ProductEntity(
    documentId: 'demo-1',
    nameEn: 'Denim Box',
    nameAr: 'بوكس الدينم',
    code: 'DEMO-1',
    description: '1x Jeans, 1x Denim jacket, 1x Shirt',
    price: 450,
    oldPrice: 1100,
    bagsLeft: 5,
    avgRating: 4.8,
    reviews: [],
    expirationsMonths: 0,
    numbersOfCalories: 0,
    unitAmount: 1,
    isFeatured: false,
    imageUrl: '',
    restaurantId: 'demo-store-1',
    restaurantName: 'Urban Threads - Sheikh Zayed',
    restaurantIsAvailable: true,
    restaurantIsOpenNow: true,
    branchLocation: _zayedAddress,
    restaurantLatitude: _zayedLat,
    restaurantLongitude: _zayedLng,
    pickupTime: 'Pickup 6:00 PM - 10:00 PM',
    detectedItems: ['1x Jeans', '1x Denim jacket', '1x Shirt'],
    sizes: ['S', 'M', 'L'],
    category: 'unisex',
  ),
  ProductEntity(
    documentId: 'demo-2',
    nameEn: 'Casual Box',
    nameAr: 'بوكس الكاجوال',
    code: 'DEMO-2',
    description: '2x T-shirt, 1x Hoodie, 1x Joggers',
    price: 350,
    oldPrice: 850,
    bagsLeft: 3,
    avgRating: 4.5,
    reviews: [],
    expirationsMonths: 0,
    numbersOfCalories: 0,
    unitAmount: 1,
    isFeatured: false,
    imageUrl: '',
    restaurantId: 'demo-store-1',
    restaurantName: 'Urban Threads - Sheikh Zayed',
    restaurantIsAvailable: true,
    restaurantIsOpenNow: true,
    branchLocation: _zayedAddress,
    restaurantLatitude: _zayedLat,
    restaurantLongitude: _zayedLng,
    pickupTime: 'Pickup 6:00 PM - 10:00 PM',
    detectedItems: ['2x T-shirt', '1x Hoodie', '1x Joggers'],
    sizes: ['M', 'L', 'XL'],
    category: 'men',
  ),
  ProductEntity(
    documentId: 'demo-3',
    nameEn: 'Summer Box',
    nameAr: 'بوكس الصيف',
    code: 'DEMO-3',
    description: '1x Linen shirt, 1x Shorts, 1x Sandals',
    price: 300,
    oldPrice: 700,
    bagsLeft: 8,
    avgRating: 4.6,
    reviews: [],
    expirationsMonths: 0,
    numbersOfCalories: 0,
    unitAmount: 1,
    isFeatured: false,
    imageUrl: '',
    restaurantId: 'demo-store-1',
    restaurantName: 'Urban Threads - Sheikh Zayed',
    restaurantIsAvailable: true,
    restaurantIsOpenNow: true,
    branchLocation: _zayedAddress,
    restaurantLatitude: _zayedLat,
    restaurantLongitude: _zayedLng,
    pickupTime: 'Pickup 6:00 PM - 10:00 PM',
    detectedItems: ['1x Linen shirt', '1x Shorts', '1x Sandals'],
    sizes: ['S', 'M'],
    category: 'women',
  ),
  ProductEntity(
    documentId: 'demo-4',
    nameEn: 'Office Box',
    nameAr: 'بوكس الشغل',
    code: 'DEMO-4',
    description: '2x Formal shirt, 1x Trousers, 1x Blazer',
    price: 600,
    oldPrice: 1500,
    bagsLeft: 2,
    avgRating: 4.9,
    reviews: [],
    expirationsMonths: 0,
    numbersOfCalories: 0,
    unitAmount: 1,
    isFeatured: false,
    imageUrl: '',
    restaurantId: 'demo-store-2',
    restaurantName: 'Cotton Corner - Zamalek',
    restaurantIsAvailable: true,
    restaurantIsOpenNow: false,
    branchLocation: _zamalekAddress,
    restaurantLatitude: _zamalekLat,
    restaurantLongitude: _zamalekLng,
    pickupTime: 'Pickup 6:00 PM - 10:00 PM',
    detectedItems: ['2x Formal shirt', '1x Trousers', '1x Blazer'],
    sizes: ['M', 'L'],
    category: 'men',
  ),
  ProductEntity(
    documentId: 'demo-5',
    nameEn: 'Kids Box',
    nameAr: 'بوكس الأطفال',
    code: 'DEMO-5',
    description: '2x Kids T-shirt, 1x Kids jeans',
    price: 250,
    oldPrice: 600,
    bagsLeft: 6,
    avgRating: 4.7,
    reviews: [],
    expirationsMonths: 0,
    numbersOfCalories: 0,
    unitAmount: 1,
    isFeatured: false,
    imageUrl: '',
    restaurantId: 'demo-store-2',
    restaurantName: 'Cotton Corner - Zamalek',
    restaurantIsAvailable: true,
    restaurantIsOpenNow: false,
    branchLocation: _zamalekAddress,
    restaurantLatitude: _zamalekLat,
    restaurantLongitude: _zamalekLng,
    pickupTime: 'Pickup 6:00 PM - 10:00 PM',
    detectedItems: ['2x Kids T-shirt', '1x Kids jeans'],
    sizes: ['XS', 'S'],
    category: 'kids',
  ),
  ProductEntity(
    documentId: 'demo-6',
    nameEn: 'Accessories Box',
    nameAr: 'بوكس الإكسسوارات',
    code: 'DEMO-6',
    description: '1x Bag, 1x Belt, 1x Scarf, 1x Sunglasses',
    price: 200,
    oldPrice: 500,
    bagsLeft: 4,
    avgRating: 4.4,
    reviews: [],
    expirationsMonths: 0,
    numbersOfCalories: 0,
    unitAmount: 1,
    isFeatured: false,
    imageUrl: '',
    restaurantId: 'demo-store-2',
    restaurantName: 'Cotton Corner - Zamalek',
    restaurantIsAvailable: true,
    restaurantIsOpenNow: false,
    branchLocation: _zamalekAddress,
    restaurantLatitude: _zamalekLat,
    restaurantLongitude: _zamalekLng,
    pickupTime: 'Pickup 6:00 PM - 10:00 PM',
    detectedItems: ['1x Bag', '1x Belt', '1x Scarf', '1x Sunglasses'],
    sizes: [],
    category: 'unisex',
  ),
];
